site_name: ELIXIR Guide for Bioschemas Annotation of Training Assets
nav:
    - About: index.md
    - Course Content:
      - "1. The annotation of websites - the basics": chapters/chapter_00.md
      - "2. Bioschemas annotation of an HTML page": chapters/chapter_01.md
      - "3. Bioschemas with Jekyll": chapters/chapter_02.md
      - "4. Bioschemas with Mkdocs": chapters/chapter_03.md
      - "5. Bioschemas with Wordpress": chapters/chapter_04.md
      - "6. Sitemap, what is it and how to create": chapters/chapter_05.md
    - "Follow up training": follow_up_training.md

theme:
  name: material
  logo: assets/images/white-orange-logo.png
  favicon: assets/images/elixir_favicon.ico
  custom_dir: overrides
  features:
    - navigation.top
    - navigation.footer
    - toc.integrate
  font: 
    text: Lato

# Repository
repo_name: elixir-europe-training/ELIXIR-TrP-Bioschema
repo_url: https://github.com/elixir-europe-training/ELIXIR-TrP-Bioschemas
edit_uri: edit/main/docs/

plugins:
  - tags:
      tags_file: keywords.md
  - search
  - bibtex:
      bib_file: "references.bib"
  - mkdocs-video # embed videos to the docs

  
# Footer
copyright: By the ELIXIR Training Platform

markdown_extensions:
  - abbr
  - def_list
  - footnotes
  - tables
  - admonition
  - addbioschemas
  - codehilite:
      guess_lang: false
  - sane_lists
  - smarty
  - toc:
      toc_depth: 3
  - pymdownx.superfences
  - attr_list
  - pymdownx.tabbed
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - neoteroi.cards


extra_css:
  - stylesheets/extra.css
  - stylesheets/neoteroi-mkdocs.css

